before_install:
- sudo add-apt-repository -y ppa:groovy-dev/grails
- sudo apt-get update
- sudo apt-get -y install grails-ppa
- sudo apt-get install grails 2.0.4
script: grails upgrade --non-interactive -y && grails test-app
